### ISSUE TITLE
How to evaluate the runtime of the model?

### ISSUE THREAD

**Issue by Zamirquito** [Zheng222/IDN-Caffe#10]
Hi @Zheng222 
I have read your paper and I find that the paper didn't tell the detail of evaluating runtime in your model and other models. I have some questions which make me confused.

1. Are the evaluating runtimes in different models used the same deep learning development kit? Since we know that caffe and pytorch would have different speed performance in the same operation. 

2. which part of time is defined as runtime? just calculate the time of model predicting or the time bicubic resizing include? 

Thanks very much!

**Comment by Zheng222** [comment]
@Zamirquito Hello, for your first question, I test other models with their own official codes. Actually, VDSR, LapSRN, and DRCN are implemented by MatConvnet. DRRN, MemNet and our IDN are used Caffe package.  The time performance of the same model upon different development kits are indeed some differences. Thus, the best practice is calculating the computational cost theoretically. 

The runtime is defined as one feed-forward time, excluding bicubic resizing. Because the bicubic interpolation operation is regarded as pre-processing. Furthermore, The execution time of bicubic in Matlab is very fast, this time is often negligible.

**Comment by Zamirquito** [comment]
OK, thanks very much, and I will close this issue.

**Comment by feiyangha** [comment]
Hello, @Zheng222.
Have you tested the number of operations(FLOPS or Multi-Add) of your IDN model? How to calculate the FLOPS on CAFFE model? Thank very much!

**Comment by feiyangha** [comment]
Hello, @Zheng222 
I am interested in your work, but it bothers me about the operations and the parameters of your IDN model.
1. Have you tested the number of operations (FLOPS or Multi-Add) of your IDN model? 
2. How to calculate the parameters of your IDN model?
 Thanks!
